// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOrOfuw0LdReGyhdwVrxwcdpp7k9Hld_Q',
    appId: '1:908727203315:web:da97b690827f0190700e86',
    messagingSenderId: '908727203315',
    projectId: 'prakflutterfirebase-be7e3',
    authDomain: 'prakflutterfirebase-be7e3.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-be7e3.appspot.com',
    measurementId: 'G-3C9VGTFN0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYmPHmgged1UC_hjrDB0kxllcm-8uzB0Y',
    appId: '1:908727203315:android:071f50ededfde536700e86',
    messagingSenderId: '908727203315',
    projectId: 'prakflutterfirebase-be7e3',
    storageBucket: 'prakflutterfirebase-be7e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-yE5LLE3DG0H7WEMgR2hG3WuxiMxmBjM',
    appId: '1:908727203315:ios:6e51442884c3ac85700e86',
    messagingSenderId: '908727203315',
    projectId: 'prakflutterfirebase-be7e3',
    storageBucket: 'prakflutterfirebase-be7e3.appspot.com',
    iosBundleId: 'com.example.praktikumFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-yE5LLE3DG0H7WEMgR2hG3WuxiMxmBjM',
    appId: '1:908727203315:ios:6e51442884c3ac85700e86',
    messagingSenderId: '908727203315',
    projectId: 'prakflutterfirebase-be7e3',
    storageBucket: 'prakflutterfirebase-be7e3.appspot.com',
    iosBundleId: 'com.example.praktikumFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOrOfuw0LdReGyhdwVrxwcdpp7k9Hld_Q',
    appId: '1:908727203315:web:6d94b3c08525518b700e86',
    messagingSenderId: '908727203315',
    projectId: 'prakflutterfirebase-be7e3',
    authDomain: 'prakflutterfirebase-be7e3.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-be7e3.appspot.com',
    measurementId: 'G-29BD3SYP5S',
  );
}
